-- NemuParfang Supabase schema
-- Paste this entire file into the Supabase SQL Editor and run it once.
-- Safe to re-run: tables, indexes, triggers, and policies are recreated idempotently.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared helper
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Public perfume catalog
-- Mirrors perfume_cleaned_export.csv without fabricating unavailable fields.
-- ---------------------------------------------------------------------------

create table if not exists public.perfumes (
  id bigint generated by default as identity primary key,
  source_url text,
  name text not null,
  brand text not null,
  country text,
  gender text not null check (gender in ('women', 'men', 'unisex')),
  rating numeric(3, 2) not null default 0 check (rating >= 0 and rating <= 5),
  review_count integer not null default 0 check (review_count >= 0),
  release_year smallint check (release_year between 1700 and 2100),
  description text,
  image_url text,
  image_url_secondary text,
  perfumer_1 text,
  perfumer_2 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text generated always as (lower(trim(name))) stored,
  description text,
  created_at timestamptz not null default now(),
  unique (normalized_name)
);

create table if not exists public.perfume_notes (
  perfume_id bigint not null references public.perfumes(id) on delete cascade,
  note_id bigint not null references public.notes(id) on delete cascade,
  note_type text not null check (note_type in ('top', 'middle', 'base')),
  position smallint not null default 1 check (position >= 1),
  primary key (perfume_id, note_id, note_type)
);

create table if not exists public.accords (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text generated always as (lower(trim(name))) stored,
  created_at timestamptz not null default now(),
  unique (normalized_name)
);

create table if not exists public.perfume_accords (
  perfume_id bigint not null references public.perfumes(id) on delete cascade,
  accord_id bigint not null references public.accords(id) on delete cascade,
  position smallint not null default 1 check (position between 1 and 10),
  primary key (perfume_id, accord_id)
);

-- ---------------------------------------------------------------------------
-- User profile and personalization
-- auth.users remains the source of truth for credentials.
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  is_public boolean not null default false,
  show_favorites boolean not null default true,
  show_reviews boolean not null default true,
  fragrance_dna jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_perfumes (
  user_id uuid not null references auth.users(id) on delete cascade,
  perfume_id bigint not null references public.perfumes(id) on delete cascade,
  collection_type text not null check (collection_type in ('favorite', 'wardrobe')),
  created_at timestamptz not null default now(),
  primary key (user_id, perfume_id, collection_type)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  perfume_id bigint not null references public.perfumes(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  content text not null check (char_length(trim(content)) between 3 and 2000),
  sentiment text check (sentiment in ('positive', 'neutral', 'negative')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, perfume_id)
);

-- ---------------------------------------------------------------------------
-- Indexes for Phase 1 browse and future API queries
-- ---------------------------------------------------------------------------

create index if not exists perfumes_brand_idx on public.perfumes (brand);
create index if not exists perfumes_gender_idx on public.perfumes (gender);
create index if not exists perfumes_country_idx on public.perfumes (country);
create index if not exists perfumes_source_url_idx on public.perfumes (source_url);
create index if not exists perfumes_rating_idx on public.perfumes (rating desc);
create index if not exists perfumes_review_count_idx on public.perfumes (review_count desc);
create index if not exists perfume_notes_note_id_idx on public.perfume_notes (note_id);
create index if not exists perfume_accords_accord_id_idx on public.perfume_accords (accord_id);
create index if not exists user_perfumes_user_id_idx on public.user_perfumes (user_id);
create index if not exists reviews_perfume_id_idx on public.reviews (perfume_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------

drop trigger if exists perfumes_set_updated_at on public.perfumes;
create trigger perfumes_set_updated_at
before update on public.perfumes
for each row execute function public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

-- Create a lightweight profile automatically after Supabase Auth signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- Public catalog is readable by everyone. Writes require service-role access.
-- User-owned records are accessible only to their owner.
-- ---------------------------------------------------------------------------

alter table public.perfumes enable row level security;
alter table public.notes enable row level security;
alter table public.perfume_notes enable row level security;
alter table public.accords enable row level security;
alter table public.perfume_accords enable row level security;
alter table public.profiles enable row level security;
alter table public.user_perfumes enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "Public can read perfumes" on public.perfumes;
create policy "Public can read perfumes"
on public.perfumes for select
using (true);

drop policy if exists "Public can read notes" on public.notes;
create policy "Public can read notes"
on public.notes for select
using (true);

drop policy if exists "Public can read perfume notes" on public.perfume_notes;
create policy "Public can read perfume notes"
on public.perfume_notes for select
using (true);

drop policy if exists "Public can read accords" on public.accords;
create policy "Public can read accords"
on public.accords for select
using (true);

drop policy if exists "Public can read perfume accords" on public.perfume_accords;
create policy "Public can read perfume accords"
on public.perfume_accords for select
using (true);

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "Public can read opted-in profiles" on public.profiles;
create policy "Public can read opted-in profiles"
on public.profiles for select
using (is_public = true);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can read their own perfume collections" on public.user_perfumes;
create policy "Users can read their own perfume collections"
on public.user_perfumes for select
using (auth.uid() = user_id);

drop policy if exists "Public can read opted-in favorite collections" on public.user_perfumes;
create policy "Public can read opted-in favorite collections"
on public.user_perfumes for select
using (
  collection_type = 'favorite'
  and exists (
    select 1
    from public.profiles
    where profiles.id = user_perfumes.user_id
      and profiles.is_public = true
      and profiles.show_favorites = true
  )
);

drop policy if exists "Users can add their own perfume collections" on public.user_perfumes;
create policy "Users can add their own perfume collections"
on public.user_perfumes for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can remove their own perfume collections" on public.user_perfumes;
create policy "Users can remove their own perfume collections"
on public.user_perfumes for delete
using (auth.uid() = user_id);

drop policy if exists "Public can read reviews" on public.reviews;
create policy "Public can read reviews"
on public.reviews for select
using (true);

drop policy if exists "Users can add their own reviews" on public.reviews;
create policy "Users can add their own reviews"
on public.reviews for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own reviews" on public.reviews;
create policy "Users can update their own reviews"
on public.reviews for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can remove their own reviews" on public.reviews;
create policy "Users can remove their own reviews"
on public.reviews for delete
using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- API grants
-- RLS still controls which rows each role can access.
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;
grant select on public.perfumes, public.notes, public.perfume_notes, public.accords, public.perfume_accords, public.reviews to anon, authenticated;
grant select on public.profiles to anon;
grant select, update on public.profiles to authenticated;
grant select on public.user_perfumes to anon;
grant select, insert, delete on public.user_perfumes to authenticated;
grant insert, update, delete on public.reviews to authenticated;
grant usage, select on all sequences in schema public to authenticated;
